// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCbmRplz_fYVkaA3nd1lITBgZA7fp8nOo',
    appId: '1:34311179316:web:c7694a218fbe54d4238e61',
    messagingSenderId: '34311179316',
    projectId: 'cafefind-76bb4',
    authDomain: 'cafefind-76bb4.firebaseapp.com',
    storageBucket: 'cafefind-76bb4.firebasestorage.app',
    measurementId: 'G-YKC66XEC8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv-72Moz_hkys7l1AfIIwNNXz_dgA3sK4',
    appId: '1:34311179316:android:f55f43acf6cb52d0238e61',
    messagingSenderId: '34311179316',
    projectId: 'cafefind-76bb4',
    storageBucket: 'cafefind-76bb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrov7wRFbcRRhywWR6WQztJ5Yk8YSV0mg',
    appId: '1:34311179316:ios:80f5f355a211d672238e61',
    messagingSenderId: '34311179316',
    projectId: 'cafefind-76bb4',
    storageBucket: 'cafefind-76bb4.firebasestorage.app',
    iosBundleId: 'com.example.cafefind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrov7wRFbcRRhywWR6WQztJ5Yk8YSV0mg',
    appId: '1:34311179316:ios:80f5f355a211d672238e61',
    messagingSenderId: '34311179316',
    projectId: 'cafefind-76bb4',
    storageBucket: 'cafefind-76bb4.firebasestorage.app',
    iosBundleId: 'com.example.cafefind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCbmRplz_fYVkaA3nd1lITBgZA7fp8nOo',
    appId: '1:34311179316:web:ce1f10a20c1a0560238e61',
    messagingSenderId: '34311179316',
    projectId: 'cafefind-76bb4',
    authDomain: 'cafefind-76bb4.firebaseapp.com',
    storageBucket: 'cafefind-76bb4.firebasestorage.app',
    measurementId: 'G-ZB98L2C0KT',
  );
}
